# Moonbloom theme for Alacritty
#
# Github: https://github.com/moonbloom-theme/alacritty
# Website: https://moonbloom.teplostanski.dev
#
# Copyright 2024, All rights reserved
# Code licensed under the MIT license
#
# @author Igor Teplostanski <igor@teplostanski.dev>
# @maintainer Igor Teplostanski <igor@teplostanski.dev>
#
# Instructions
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[colors.primary]
background = "#1D1E27"
foreground = "#D1D2E8"
dim_foreground = "#9B9BBA"
bright_foreground = "#E1E2ED"

[colors.cursor]
text = "#1A1B21"
cursor = "#D1D2E8"

[colors.vi_mode_cursor]
text = "#1D1E27"
cursor = "#6EB4E0"

[colors.search.matches]
foreground = "#1D1E27"
background = "#D1D2E8"

[colors.search.focused_match]
foreground = "#1D1E27"
background = "#A1D79F"

[colors.footer_bar]
foreground = "#1D1E27"
background = "#D1D2E8"

[colors.hints.start]
foreground = "#1D1E27"
background = "#D9B469"

[colors.hints.end]
foreground = "#1D1E27"
background = "#D1D2E8"

[colors.selection]
text = "#1A1B21"
background = "#9B9BBA"

[colors.normal]
black = "#1A1B21"
red = "#E66D75"
green = "#93c591"
yellow = "#D9B469"
blue = "#5A9BCF"
magenta = "#BB83D8"
cyan = "#4FA8B8"
white = "#9B9BBA"

[colors.bright]
black = "#8282a9"
red = "#F17C88"
green = "#A1D79F"
yellow = "#E8C87E"
blue = "#6EB4E0"
magenta = "#C993E9"
cyan = "#68C7D6"
white = "#E1E2ED"
